<?php

namespace Database\Seeders;

use App\Models\Guru;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class GuruSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $teachers = [
            [
                "NAMA" => "Ir. Bahrun Amin, S.T., IPM",
                "TEMPAT LAHIR" => "Muara Badak",
                "TANGGAL LAHIR" => "1982-03-11",
                "TMT PENGANGKATAN AWAL" => "2008-01-14",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "16 Tahun 9 Bulan 21 Hari",
                "TOTAL" => "16 Tahun 9 Bulan 21 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "L",
                "JURUSAN" => "Teknik Mesin",
                "TAHUN IJAZAH" => "2012",
                "NO NPY" => "198203110720080109",
                "NO NIK" => "6474021103820003",
                "NO NUPTK" => "4643760661130172",
                "JABATAN" => "Kepala Sekolah",
                "JENIS PTK" => "Kepala Sekolah",
                "ALAMAT KTP" => "Jl.Merah Delima 01 RT.34",
                "KELURAHAN" => "Berbas Tengah",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "082159592527",
                "ALAMA EMAIL" => "bahrun_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Dedy Daud, S.T",
                "TEMPAT LAHIR" => "Sidrap",
                "TANGGAL LAHIR" => "1983-08-18",
                "TMT PENGANGKATAN AWAL" => "2013-07-09",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "11 Tahun 3 Bulan 26 Hari",
                "TOTAL" => "11 Tahun 3 Bulan 26 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "L",
                "JURUSAN" => "Teknik Mesin",
                "TAHUN IJAZAH" => "D3-2004, S1 2023",
                "NO NPY" => "198308180720130110",
                "NO NIK" => "6474021808830003",
                "NO NUPTK" => null,
                "JABATAN" => "Guru Produktif, KAKON TAB",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl.Patimura Gg Atletik 20 No 101",
                "KELURAHAN" => "Api-Api",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "085250374567",
                "ALAMA EMAIL" => "dedy_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Maria Susanti, S.H",
                "TEMPAT LAHIR" => "Surabaya",
                "TANGGAL LAHIR" => "1966-02-26",
                "TMT PENGANGKATAN AWAL" => "2007-07-18",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "17 Tahun 3 Bulan 17 Hari",
                "TOTAL" => "17 Tahun 3 Bulan 17 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "P",
                "JURUSAN" => "Hukum",
                "TAHUN IJAZAH" => "2013",
                "NO NPY" => "196602260720070202",
                "NO NIK" => "6474036602660002",
                "NO NUPTK" => "5558744646300022",
                "JABATAN" => "Ketua Yayasan, Guru BK",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl.Sumatra Hop IV No.180 RT. 02",
                "KELURAHAN" => "Gunung Telihan",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "081253042172",
                "ALAMA EMAIL" => "maria_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Nelfi Ilham K, S.E",
                "TEMPAT LAHIR" => "Ujung Pandang",
                "TANGGAL LAHIR" => "1973-04-02",
                "TMT PENGANGKATAN AWAL" => "2011-02-05",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "13 Tahun 8 Bulan 30 Hari",
                "TOTAL" => "13 Tahun 8 Bulan 30 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "KRISTEN",
                "JENIS KELAMIN" => "P",
                "JURUSAN" => "Akutansi",
                "TAHUN IJAZAH" => "1996",
                "NO NPY" => "197304020120100215",
                "NO NIK" => "6474024204730002",
                "NO NUPTK" => "1734751652230112",
                "JABATAN" => "Guru Mapel, Wali Kelas, Rokris",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl.AP Mangkunegoro Gg.Mutiara No 11 RT. 07",
                "KELURAHAN" => "Berbas Tengah",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "081253657054",
                "ALAMA EMAIL" => "nelfik_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Aminatus Zahrah, S.Pd",
                "TEMPAT LAHIR" => "Pamekasan",
                "TANGGAL LAHIR" => "1989-09-25",
                "TMT PENGANGKATAN AWAL" => "2008-07-01",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "6 Tahun 11 Bulan 5 Hari",
                "TOTAL" => "16 Tahun 4 Bulan 3 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "P",
                "JURUSAN" => "Pendidikan Matematika",
                "TAHUN IJAZAH" => "2012",
                "NO NPY" => "198909250720170235",
                "NO NIK" => "3528106509890001",
                "NO NUPTK" => "7257767668130143",
                "JABATAN" => "Guru Mapel",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl. Karya BTN KCY No. 56 RT. 10",
                "KELURAHAN" => "Api-Api",
                "ALAMAT DOMISILI" => "Jl. Labu kuning no.56, RT.19 Perumahan GTS",
                "NO HP" => "082331309099",
                "ALAMA EMAIL" => "zahra_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Salma Wati, S.Pd",
                "TEMPAT LAHIR" => "Bontang",
                "TANGGAL LAHIR" => "1992-04-20",
                "TMT PENGANGKATAN AWAL" => "2016-10-03",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "8 Tahun 1 Bulan 1 Hari",
                "TOTAL" => "8 Tahun 1 Bulan 1 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "P",
                "JURUSAN" => "Pendidikan Bahasa Inggris",
                "TAHUN IJAZAH" => "2015",
                "NO NPY" => "199204200720160234",
                "NO NIK" => "6474026004920004",
                "NO NUPTK" => "6752770671130112",
                "JABATAN" => "Guru Mapel, Wali Kelas",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl. Mutiara RT 08",
                "KELURAHAN" => "Berbas Tengah",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "082346394934",
                "ALAMA EMAIL" => "salmawati_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Eko Armiyanto, S.Pd, S.T",
                "TEMPAT LAHIR" => "Samarinda",
                "TANGGAL LAHIR" => "1974-10-29",
                "TMT PENGANGKATAN AWAL" => "2000-07-07",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "6 Tahun 3 Bulan 19 Hari",
                "TOTAL" => "24 Tahun 3 Bulan 28 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "L",
                "JURUSAN" => "S1 - Pendidikan Matematika, D3 - Teknik Mesin, S-1 Teknik",
                "TAHUN IJAZAH" => "S1 - 2009, D3 - 1996, S1-2023",
                "NO NPY" => "197410290720160137",
                "NO NIK" => "6474012910740003",
                "NO NUPTK" => "6361752654200013",
                "JABATAN" => "Guru Produktif, Waka Kesiswaan",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl. Patimura Gg.Atletik 21 No.76 RT. 14",
                "KELURAHAN" => "Api-Api",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "081348725366",
                "ALAMA EMAIL" => "eko_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Ir. Hanif Hariyadi, S.T",
                "TEMPAT LAHIR" => "Surabaya",
                "TANGGAL LAHIR" => "1977-09-12",
                "TMT PENGANGKATAN AWAL" => "2019-07-01",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "5 Tahun 4 Bulan 3 Hari",
                "TOTAL" => "5 Tahun 4 Bulan 3 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "L",
                "JURUSAN" => "Teknik Mesin",
                "TAHUN IJAZAH" => "2015",
                "NO NPY" => "197709120720180140",
                "NO NIK" => "6474011209770007",
                "NO NUPTK" => "6244755656130113",
                "JABATAN" => "Guru Produktif",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl. Patimura Gg. Atletik 8 RT. 42",
                "KELURAHAN" => "Api-Api",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "08125477757",
                "ALAMA EMAIL" => "hanif_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Jasman  Japar D, S.S",
                "TEMPAT LAHIR" => "Bule",
                "TANGGAL LAHIR" => "1973-05-04",
                "TMT PENGANGKATAN AWAL" => "2008-07-29",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "7 Tahun 0 Bulan 2 Hari",
                "TOTAL" => "16 Tahun 3 Bulan 6 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "L",
                "JURUSAN" => "Sastra Indonesia",
                "TAHUN IJAZAH" => "2006",
                "NO NPY" => "197305040720180147",
                "NO NIK" => "6474010405730005",
                "NO NUPTK" => "2836751653200042",
                "JABATAN" => "Operator Yayasan",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl. KS. Tubun Gg. Bersama No.26 RT. 32",
                "KELURAHAN" => "Api-Api",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "082148968855",
                "ALAMA EMAIL" => "jasman_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Agus Sutrisno, S. Pd",
                "TEMPAT LAHIR" => "Pamekasan",
                "TANGGAL LAHIR" => "1988-08-03",
                "TMT PENGANGKATAN AWAL" => "2009-07-01",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "5 Tahun 3 Bulan 18 Hari",
                "TOTAL" => "15 Tahun 4 Bulan 3 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "L",
                "JURUSAN" => "Pendidikan Matematika",
                "TAHUN IJAZAH" => "2011",
                "NO NPY" => "198808030720190156",
                "NO NIK" => "3528030308880001",
                "NO NUPTK" => "9135766667130093",
                "JABATAN" => "Guru Mapel",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl. Karya BTN KCY No. 56 RT. 10",
                "KELURAHAN" => "Api-Api",
                "ALAMAT DOMISILI" => "Jl. Labu kuning No. 56, RT.19 Perumahan GTS",
                "NO HP" => "082251324622",
                "ALAMA EMAIL" => "agus_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Herawati Hakim, S.T",
                "TEMPAT LAHIR" => "Pinrang",
                "TANGGAL LAHIR" => "1976-10-26",
                "TMT PENGANGKATAN AWAL" => "2009-07-01",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "5 Tahun 1 Bulan 23 Hari",
                "TOTAL" => "15 Tahun 4 Bulan 3 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "P",
                "JURUSAN" => "Teknik Manajemen Industri",
                "TAHUN IJAZAH" => "2001",
                "NO NPY" => "197610260720180248",
                "NO NIK" => "6474016610760004",
                "NO NUPTK" => "5358754656210083",
                "JABATAN" => "Guru Produktif, KAKON TMI & DPIB",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl. Kapal Layar 5 RT.20",
                "KELURAHAN" => "Loktuan",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "085391771489",
                "ALAMA EMAIL" => "herawati_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Syahiruddin, S.Pd",
                "TEMPAT LAHIR" => "Barru",
                "TANGGAL LAHIR" => "1980-05-02",
                "TMT PENGANGKATAN AWAL" => "2018-01-02",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "3 Tahun 3 Bulan 30 Hari",
                "TOTAL" => "6 Tahun 10 Bulan 2 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "L",
                "JURUSAN" => "Pendidikan Agama Islam",
                "TAHUN IJAZAH" => "2019",
                "NO NPY" => "198005020720210160",
                "NO NIK" => "6472030205800006",
                "NO NUPTK" => "2834758659130232",
                "JABATAN" => "Guru Mapel, Waka Kurikulum, Rohis",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl. Gamelan No. 8 RT. 15",
                "KELURAHAN" => "Bontang Baru",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "082155414085",
                "ALAMA EMAIL" => "syahiruddin_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Noviani, S.Tr. Kom",
                "TEMPAT LAHIR" => "Loa Janan",
                "TANGGAL LAHIR" => "1996-11-04",
                "TMT PENGANGKATAN AWAL" => "2021-07-05",
                "HARI INI" => "2023-07-23",
                "MASA KERJA" => "2 Tahun 0 Bulan 18 Hari",
                "TOTAL" => "2 Tahun 0 Bulan 18 Hari",
                "PENDIDIKAN TERAKHIR" => "D-4",
                "AGAMA" => "KRISTEN",
                "JENIS KELAMIN" => "p",
                "JURUSAN" => "Teknologi Rekayasa Perangkat Lunak",
                "TAHUN IJAZAH" => "2019",
                "NO NPY" => "199611040720210270",
                "NO NIK" => "6474034411960001",
                "NO NUPTK" => null,
                "JABATAN" => "Guru Produktif, Wali Kelas",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl. Banjarmasin No.40",
                "KELURAHAN" => "Gn. Telihan",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "082155051539",
                "ALAMA EMAIL" => "noviani_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Siti Nur Fatimah, S.Pd",
                "TEMPAT LAHIR" => "Bontang",
                "TANGGAL LAHIR" => "1998-06-03",
                "TMT PENGANGKATAN AWAL" => "2021-07-05",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "3 Tahun 3 Bulan 30 Hari",
                "TOTAL" => "3 Tahun 3 Bulan 30 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "P",
                "JURUSAN" => "Bimbingan dan Konseling",
                "TAHUN IJAZAH" => "2021",
                "NO NPY" => "199806030720210271",
                "NO NIK" => "6474024306980006",
                "NO NUPTK" => null,
                "JABATAN" => "Guru BK, Wali Kelas",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl. Belanak RT. 21 Rawa Indah",
                "KELURAHAN" => "Tanjung Laut Indah",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "085348799849",
                "ALAMA EMAIL" => "fatimah_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Sabrina, S.Ag",
                "TEMPAT LAHIR" => "Ma'rang",
                "TANGGAL LAHIR" => "1968-09-29",
                "TMT PENGANGKATAN AWAL" => "2001-01-01",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "17 Tahun 3 Bulan 17 Hari",
                "TOTAL" => "23 Tahun 10 Bulan 3 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "P",
                "JURUSAN" => "Perdata Pidana Islam",
                "TAHUN IJAZAH" => "1997",
                "NO NPY" => "196809290720080213",
                "NO NIK" => "6474016909680003",
                "NO NUPTK" => "9261746647300013",
                "JABATAN" => "Guru Mapel",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl.Pelabuhan II RT.09",
                "KELURAHAN" => "Tanjung Laut Indah",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "081347155607",
                "ALAMA EMAIL" => "sabrina_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Muhammad April Gutadi, S.Tr.T",
                "TEMPAT LAHIR" => "Bontang",
                "TANGGAL LAHIR" => "1997-04-01",
                "TMT PENGANGKATAN AWAL" => "2021-07-05",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "3 Tahun 3 Bulan 30 Hari",
                "TOTAL" => "3 Tahun 3 Bulan 30 Hari",
                "PENDIDIKAN TERAKHIR" => "D-4",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "L",
                "JURUSAN" => "Teknik Mesin",
                "TAHUN IJAZAH" => "2019",
                "NO NPY" => "199704010720210164",
                "NO NIK" => "6474010104680002",
                "NO NUPTK" => null,
                "JABATAN" => "Guru Produktif",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl. RE Martadinata RT. 43 ",
                "KELURAHAN" => "Loktuan",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "081273593340",
                "ALAMA EMAIL" => "gutadi_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Pandu Pasa, S.Si",
                "TEMPAT LAHIR" => "Surabaya",
                "TANGGAL LAHIR" => "1987-05-19",
                "TMT PENGANGKATAN AWAL" => "2019-01-07",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "5 Tahun 4 Bulan 3 Hari",
                "TOTAL" => "5 Tahun 9 Bulan 28 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "L",
                "JURUSAN" => "Sains",
                "TAHUN IJAZAH" => "2010",
                "NO NPY" => "198705190720190168",
                "NO NIK" => "3578201905870002",
                "NO NUPTK" => null,
                "JABATAN" => "Guru Produktif, Operator Dapodik Sekolah",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl.Sumatra Hop IV No.180 RT. 02",
                "KELURAHAN" => "Gunung Telihan",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "081233399869",
                "ALAMA EMAIL" => "pandu_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "M. Choirul Anam, S.T",
                "TEMPAT LAHIR" => "Lamongan",
                "TANGGAL LAHIR" => "1993-02-02",
                "TMT PENGANGKATAN AWAL" => "2013-06-01",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "1 Tahun 4 Bulan 1 Hari",
                "TOTAL" => "11 Tahun 5 Bulan 3 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "L",
                "JURUSAN" => "Teknik Mesin",
                "TAHUN IJAZAH" => "2019",
                "NO NPY" => "199302020720230176",
                "NO NIK" => "6474020202930004",
                "NO NUPTK" => null,
                "JABATAN" => "Guru Produktif, Wali Kelas",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl. Sutan Syarir Cumi-Cumi 1 ",
                "KELURAHAN" => "Tanjung Laut",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "085250755571",
                "ALAMA EMAIL" => "anam_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Alfian Bagus Eka Putra, S.T",
                "TEMPAT LAHIR" => "Lamongan",
                "TANGGAL LAHIR" => "1995-12-15",
                "TMT PENGANGKATAN AWAL" => "2021-07-05",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "3 Tahun 3 Bulan 30 Hari",
                "TOTAL" => "3 Tahun 3 Bulan 30 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "L",
                "JURUSAN" => "Teknik Mesin",
                "TAHUN IJAZAH" => "2019",
                "NO NPY" => "199512150720210159",
                "NO NIK" => "6474011512950006",
                "NO NUPTK" => null,
                "JABATAN" => "Guru Produktif",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl. Polo Air I RT. 21",
                "KELURAHAN" => "Api-Api",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "082225962015",
                "ALAMA EMAIL" => "alfian_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Fandy Andriyadi, A.Md",
                "TEMPAT LAHIR" => "Samarinda",
                "TANGGAL LAHIR" => "1984-12-31",
                "TMT PENGANGKATAN AWAL" => "2013-07-15",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "11 Tahun 3 Bulan 20 Hari",
                "TOTAL" => "11 Tahun 3 Bulan 20 Hari",
                "PENDIDIKAN TERAKHIR" => "D-3",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "L",
                "JURUSAN" => "Teknik Mesin",
                "TAHUN IJAZAH" => "2006",
                "NO NPY" => "198412310720130126",
                "NO NIK" => "6474023112840015",
                "NO NUPTK" => null,
                "JABATAN" => "Guru Produktif, Waka Sarpras",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl. Selat Karimata 1 RT 26",
                "KELURAHAN" => "Tanjung Laut",
                "ALAMAT DOMISILI" => null,
                "NO HP" => null,
                "ALAMA EMAIL" => "fandyandriyadi@gmail.com",
            ],
            [
                "NAMA" => "Henny Srihantika, S.Pd",
                "TEMPAT LAHIR" => "Bontang",
                "TANGGAL LAHIR" => "2001-01-24",
                "TMT PENGANGKATAN AWAL" => "2024-02-01",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "0 Tahun 9 Bulan 3 Hari",
                "TOTAL" => "0 Tahun 9 Bulan 3 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "P",
                "JURUSAN" => "Pendidikan Fisika",
                "TAHUN IJAZAH" => "2023",
                "NO NPY" => "200101240220240281",
                "NO NIK" => "6474036401010003",
                "NO NUPTK" => null,
                "JABATAN" => "Guru Mapel, Wali Kelas",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl. Banjarmasin RT. 21 Kec. Bontang Barat",
                "KELURAHAN" => "Gunung Telihan ",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "08990710689",
                "ALAMA EMAIL" => "henny@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Tetuka Wira Setya, A.Md",
                "TEMPAT LAHIR" => "Bontang",
                "TANGGAL LAHIR" => "2001-03-31",
                "TMT PENGANGKATAN AWAL" => "2024-01-15",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "0 Tahun 9 Bulan 20 Hari",
                "TOTAL" => "0 Tahun 9 Bulan 20 Hari",
                "PENDIDIKAN TERAKHIR" => "D-3",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "L",
                "JURUSAN" => "Teknik Bangunan Kapal",
                "TAHUN IJAZAH" => "2022",
                "NO NPY" => "200103310120240178",
                "NO NIK" => "6474013103010005",
                "NO NUPTK" => null,
                "JABATAN" => "Guru Produktif, Wali Kelas",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl. Irstampubolon No. 42 HOP IV Kompleks PTB RT. 24 Kec. Bontang Utara",
                "KELURAHAN" => "Gunung Elai",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "089689313048",
                "ALAMA EMAIL" => "wira@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Darmawan, A.Md",
                "TEMPAT LAHIR" => "Bontan",
                "TANGGAL LAHIR" => "1981-08-21",
                "TMT PENGANGKATAN AWAL" => "2024-01-15",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "0 Tahun 9 Bulan 20 Hari",
                "TOTAL" => "0 Tahun 9 Bulan 20 Hari",
                "PENDIDIKAN TERAKHIR" => "D-3",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "L",
                "JURUSAN" => "Teknik Sipil",
                "TAHUN IJAZAH" => "2007",
                "NO NPY" => "198108210120240179",
                "NO NIK" => "6474032108810003",
                "NO NUPTK" => null,
                "JABATAN" => "Guru Produktif",
                "JENIS PTK" => "Guru",
                "ALAMAT KTP" => "Jl. Jambu 2 No. 43 BTN PKT RT. 24 Kec. Bontang Barat ",
                "KELURAHAN" => "Belimbing",
                "ALAMAT DOMISILI" => null,
                "NO HP" => null,
                "ALAMA EMAIL" => "darmawan@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Wirdan Ramli, S.E",
                "TEMPAT LAHIR" => "Samarinda",
                "TANGGAL LAHIR" => "1982-04-04",
                "TMT PENGANGKATAN AWAL" => "2019-07-16",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "5 Tahun 3 Bulan 19 Hari",
                "TOTAL" => "5 Tahun 3 Bulan 19 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "L",
                "JURUSAN" => "Ekonomi",
                "TAHUN IJAZAH" => "2016",
                "NO NPY" => "198204040720180145",
                "NO NIK" => "6474020404820016",
                "NO NUPTK" => "1736760661130282",
                "JABATAN" => "Guru Mapel, Bendahara BOSDA, Bagian Umum",
                "JENIS PTK" => "Tendik",
                "ALAMAT KTP" => "Jl.Sidrap RT 21",
                "KELURAHAN" => "Guntung",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "08115441225",
                "ALAMA EMAIL" => "wirdan_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Haisah, S.KM",
                "TEMPAT LAHIR" => "Bontang",
                "TANGGAL LAHIR" => "1991-01-23",
                "TMT PENGANGKATAN AWAL" => "2017-07-16",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "7 Tahun 3 Bulan 19 Hari",
                "TOTAL" => "7 Tahun 3 Bulan 19 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "P",
                "JURUSAN" => "Kesehatan Masyarakat",
                "TAHUN IJAZAH" => "2013",
                "NO NPY" => "199101230720180246",
                "NO NIK" => "6474026301910002",
                "NO NUPTK" => "3455769670230152",
                "JABATAN" => "Ka TU, Bendahara BOSNAS, PJ UKS",
                "JENIS PTK" => "Tendik",
                "ALAMAT KTP" => "Jl. P.Antasari Rt.06",
                "KELURAHAN" => "Berbas Pantai",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "081347033411",
                "ALAMA EMAIL" => "haisah_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Eka Ratnasari, S.Pd",
                "TEMPAT LAHIR" => "Benua Lawas",
                "TANGGAL LAHIR" => "1993-06-06",
                "TMT PENGANGKATAN AWAL" => "2017-06-02",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "4 Tahun 3 Bulan 29 Hari",
                "TOTAL" => "7 Tahun 5 Bulan 2 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "P",
                "JURUSAN" => "Pendidikan Kimia",
                "TAHUN IJAZAH" => "2016",
                "NO NPY" => "199306060720200257",
                "NO NIK" => "6474014606930006",
                "NO NUPTK" => "2938771672230182",
                "JABATAN" => "Staff TU, Wali Kelas",
                "JENIS PTK" => "Tendik",
                "ALAMAT KTP" => "Jl. A. Yani Gg.Karya Rt.005",
                "KELURAHAN" => "Api-Api",
                "ALAMAT DOMISILI" => "Jl. HM Ardans RT. 24 Kel. Satimpo",
                "NO HP" => "082251088837",
                "ALAMA EMAIL" => "eka_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Ferry Novyanto",
                "TEMPAT LAHIR" => "Bontang",
                "TANGGAL LAHIR" => "2001-11-01",
                "TMT PENGANGKATAN AWAL" => "2022-06-27",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "2 Tahun 4 Bulan 8 Hari",
                "TOTAL" => "2 Tahun 4 Bulan 8 Hari",
                "PENDIDIKAN TERAKHIR" => "SMK",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "L",
                "JURUSAN" => "Teknik Alat Berat",
                "TAHUN IJAZAH" => "2022",
                "NO NPY" => "200111010620220169",
                "NO NIK" => "6474030111010002",
                "NO NUPTK" => null,
                "JABATAN" => "Kepala Workshop",
                "JENIS PTK" => "Tendik",
                "ALAMAT KTP" => "Jl. Denpasar VI RT 7",
                "KELURAHAN" => "Gunung Telihan",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "081256831236",
                "ALAMA EMAIL" => "fery_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Diny Marina, S.Tr. Kom",
                "TEMPAT LAHIR" => "Bontang",
                "TANGGAL LAHIR" => "2000-03-14",
                "TMT PENGANGKATAN AWAL" => "2023-05-03",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "1 Tahun 6 Bulan 1 Hari",
                "TOTAL" => "1 Tahun 6 Bulan 1 Hari",
                "PENDIDIKAN TERAKHIR" => "D-4",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "P",
                "JURUSAN" => "Teknik Informatika Multimedia",
                "TAHUN IJAZAH" => "2022",
                "NO NPY" => "200003140520230274",
                "NO NIK" => "6474025403000005",
                "NO NUPTK" => null,
                "JABATAN" => "Bendahara Komite",
                "JENIS PTK" => "Tendik",
                "ALAMAT KTP" => "Jl. Selat Madura No. 43 RT.08",
                "KELURAHAN" => "Tanjung Laut",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "081527712374",
                "ALAMA EMAIL" => "diny@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Rizky Nadila Handayani",
                "TEMPAT LAHIR" => "Bontang",
                "TANGGAL LAHIR" => "2002-01-05",
                "TMT PENGANGKATAN AWAL" => "2023-05-03",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "1 Tahun 6 Bulan 1 Hari",
                "TOTAL" => "1 Tahun 6 Bulan 1 Hari",
                "PENDIDIKAN TERAKHIR" => "SMK",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "P",
                "JURUSAN" => "Teknik Alat Berat",
                "TAHUN IJAZAH" => "2021",
                "NO NPY" => "200201050520230275",
                "NO NIK" => "6474014501020001",
                "NO NUPTK" => null,
                "JABATAN" => "Kepala Perpustakaan, Kepala Laboratorium Komputer",
                "JENIS PTK" => "Tendik",
                "ALAMAT KTP" => "Jl. Brigjen Katamso RT. 16",
                "KELURAHAN" => "Gunung Elai",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "087770000023",
                "ALAMA EMAIL" => "nadila_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Sunarmi Sirajuddin",
                "TEMPAT LAHIR" => "Bontang",
                "TANGGAL LAHIR" => "1988-10-20",
                "TMT PENGANGKATAN AWAL" => "2012-01-05",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "1 Tahun 4 Bulan 1 Hari",
                "TOTAL" => "12 Tahun 9 Bulan 30 Hari",
                "PENDIDIKAN TERAKHIR" => "PAKET C",
                "AGAMA" => "ISLAM",
                "JENIS KELAMIN" => "P",
                "JURUSAN" => null,
                "TAHUN IJAZAH" => "2007",
                "NO NPY" => "198810200720230277",
                "NO NIK" => "6474026010880004",
                "NO NUPTK" => null,
                "JABATAN" => null,
                "JENIS PTK" => "Tendik",
                "ALAMAT KTP" => "Jl. Berlian RT. 21 No. 21 No. 01 Kec. Bontang Selatan",
                "KELURAHAN" => "Tanjung Laut",
                "ALAMAT DOMISILI" => null,
                "NO HP" => "085246926284",
                "ALAMA EMAIL" => "sunarmi_smk@nusantara-mandiri.sch.id",
            ],
            [
                "NAMA" => "Lady Muana Olifia Silalahi, S.IP",
                "TEMPAT LAHIR" => "Bontang",
                "TANGGAL LAHIR" => "1991-12-02",
                "TMT PENGANGKATAN AWAL" => "2024-01-17",
                "HARI INI" => "2024-11-04",
                "MASA KERJA" => "0 Tahun 9 Bulan 18 Hari",
                "TOTAL" => "0 Tahun 9 Bulan 18 Hari",
                "PENDIDIKAN TERAKHIR" => "S-1",
                "AGAMA" => "KRISTEN",
                "JENIS KELAMIN" => "P",
                "JURUSAN" => "Ilmu Pemerintahan",
                "TAHUN IJAZAH" => "2017",
                "NO NPY" => "199112020120240280",
                "NO NIK" => "6474034212910004",
                "NO NUPTK" => null,
                "JABATAN" => "Kepala Toolroom, Wali Kelas",
                "JENIS PTK" => "Tendik",
                "ALAMAT KTP" => null,
                "KELURAHAN" => null,
                "ALAMAT DOMISILI" => null,
                "NO HP" => null,
                "ALAMA EMAIL" => "muana@nusantara-mandiri.sch.id",
            ]
        ];
        
        foreach ($teachers as $teacher) {
            $user = User::create([
                "name" => $teacher["NAMA"],
                "email" => $teacher["ALAMA EMAIL"],
                "password" => Hash::make("password"),
            ]);

            Guru::create([
                "user_id" => $user->id,
                "nik" => $teacher["NO NIK"],
                "nuptk" => $teacher["NO NUPTK"],
                "npy" => $teacher["NO NPY"],
                "tempat_lahir" => $teacher["TEMPAT LAHIR"],
                "tanggal_lahir" => $teacher["TANGGAL LAHIR"],
                "jenis_kelamin" => ($teacher["JENIS KELAMIN"] === "L") ? "Laki-laki" : "Perempuan",
                "agama" => $teacher["AGAMA"],
                "studi_terakhir" => $teacher["PENDIDIKAN TERAKHIR"],
                "tahun_gabung" => $teacher["TMT PENGANGKATAN AWAL"],
                "alamat" => $teacher["ALAMAT DOMISILI"],
                "no_telp" => $teacher["NO HP"],
            ]);
        }
    }
}
