<?php

namespace Database\Seeders;

use App\Models\Siswa;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $students = [
            [
                "NIS" => "20210201393",
                "NAMA" => "AHMAD DEFRI DEWANGSYAH",
                "NISN" => "0041422168",
                "Tempat lahir" => "MALANG",
                "Tgl lahir" => "2004-05-21",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "ISLAM",
                "alamat" => "JL. SOEKARNO HATTA RT. 25 KEL. GUNUNG TELIHAN KEC. BONTANG BARAT, BONTANG",
                "No. Telp" => "082154546613",
                "kelas" => "",
                "tgl masuk" => "7/5/21",
            ],
            [
                "NIS" => "20210201394",
                "NAMA" => "ALBISMA DHARMA PUTRA",
                "NISN" => "0057671503",
                "Tempat lahir" => "BONTANG",
                "Tgl lahir" => "2005-12-12",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "ISLAM",
                "alamat" => "JL. DI PANJAITAN RT. 27 KEL. API-API KEC. BONTANG UTARA, BONTANG",
                "No. Telp" => "081350510080 / 082157000364",
                "kelas" => "",
                "tgl masuk" => "7/5/21",
            ],
            [
                "NIS" => "20210201395",
                "NAMA" => "ALVINO FRANSISCO",
                "NISN" => "0065103815",
                "Tempat lahir" => "SAMARINDA",
                "Tgl lahir" => "2006-09-08",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "KRISTEN",
                "alamat" => "JL. TARAKAN 4 RT 18 BONTANG",
                "No. Telp" => "082117043440",
                "kelas" => "",
                "tgl masuk" => "7/5/21",
            ],
            [
                "NIS" => "20210201396",
                "NAMA" => "ANDI ARYA ERLANGGA",
                "NISN" => "0040795591",
                "Tempat lahir" => "BONTANG",
                "Tgl lahir" => "2004-06-17",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "ISLAM",
                "alamat" => "JL. KAPAL SELAM 3 RT. 016 LOK TUAN BONTANG UTARA",
                "No. Telp" => "081346258184",
                "kelas" => "",
                "tgl masuk" => "7/5/21",
            ],
            [
                "NIS" => "20210201416",
                "NAMA" => "CATUR SETIAWAN",
                "NISN" => "0050818270",
                "Tempat lahir" => "BONTANG",
                "Tgl lahir" => "2005-02-21",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "ISLAM",
                "alamat" => "JL. KEBUN SALAK GUNTUNG",
                "No. Telp" => "0895704427389",
                "kelas" => "",
                "tgl masuk" => "7/5/21",
            ],
            [
                "NIS" => "20210201398",
                "NAMA" => "CHRISTIAN INDRA MANGOPANG",
                "NISN" => "0069801945",
                "Tempat lahir" => "BONTANG",
                "Tgl lahir" => "2006-04-09",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "KRISTEN",
                "alamat" => "JL.S PARMAN GG.GOTONG ROYONG RT.49  KEL.BELIMBING BONTANG BARAT",
                "No. Telp" => "082153840984",
                "kelas" => "",
                "tgl masuk" => "7/5/21",
            ],
            [
                "NIS" => "20210201397",
                "NAMA" => "CHRISTOPHER DICAPRIO MADA",
                "NISN" => "0061919591",
                "Tempat lahir" => "SANGATTA",
                "Tgl lahir" => "2006-12-30",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "KRISTEN",
                "alamat" => "JL.SION RT.05 KANAAN",
                "No. Telp" => "081350421621",
                "kelas" => "",
                "tgl masuk" => "7/5/21",
            ],
            [
                "NIS" => "20220200521",
                "NAMA" => "DIMAS RAMA GUMILANG ",
                "NISN" => "0058505975",
                "Tempat lahir" => "BONTANG",
                "Tgl lahir" => "2005-10-03",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "ISLAM",
                "alamat" => "JL.PONTIANAK GG PONTIANAK II RT.26 KEL.GUNUNG TELIHAN BONTANG BARAT",
                "No. Telp" => "085759628849",
                "kelas" => "",
                "tgl masuk" => "7/11/22",
            ],
            [
                "NIS" => "20210201399",
                "NAMA" => "EGIEY SAPUTRA",
                "NISN" => "0066149418",
                "Tempat lahir" => "JAHAB",
                "Tgl lahir" => "2005-05-06",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "ISLAM",
                "alamat" => "JL.PONGTIKU RT.06 KEL.KANAAN BONTANG BARAT",
                "No. Telp" => "085348386437",
                "kelas" => "",
                "tgl masuk" => "7/5/21",
            ],
            [
                "NIS" => "20210201401",
                "NAMA" => "FAHMI FERDIANSYAH",
                "NISN" => "0057096348",
                "Tempat lahir" => "PAMEKASAN",
                "Tgl lahir" => "2005-12-27",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "ISLAM",
                "alamat" => "JL. POROS BONTANG-SANGATTA KEL. SUKA RAHMAT KEC. TELUK PANDAN, KUTAI TIMUR",
                "No. Telp" => "085332395615",
                "kelas" => "",
                "tgl masuk" => "7/5/21",
            ],
            [
                "NIS" => "20200201322",
                "NAMA" => "HAFID AFRIZAL",
                "NISN" => "0057406777",
                "Tempat lahir" => "SAMARINDA",
                "Tgl lahir" => "2005-06-08",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "ISLAM",
                "alamat" => "TELUK PANDAI KUTAI TIMUR",
                "No. Telp" => "081326507532",
                "kelas" => "",
                "tgl masuk" => "5/5/20",
            ],
            [
                "NIS" => "20210201402",
                "NAMA" => "HAIKAL IRIAWAN",
                "NISN" => "0062351989",
                "Tempat lahir" => "BONTANG",
                "Tgl lahir" => "2006-03-31",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "ISLAM",
                "alamat" => "JL.KARYA BAKTI RT 04 KELURAHAN BONTAG LESTARI",
                "No. Telp" => "081350920255",
                "kelas" => "",
                "tgl masuk" => "7/5/21",
            ],
            [
                "NIS" => "20210201403",
                "NAMA" => "JUAN PABLO PARULIAN SIREGAR",
                "NISN" => "0065967342",
                "Tempat lahir" => "BONTANG",
                "Tgl lahir" => "2006-06-19",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "KRISTEN",
                "alamat" => "JL. PONGTIKU RT. 01 KEL. KANAAN KEC. BONTANG BARAT",
                "No. Telp" => "081255663466",
                "kelas" => "",
                "tgl masuk" => "7/5/21",
            ],
            [
                "NIS" => "20210201422",
                "NAMA" => "KHALID GIBRALTAR",
                "NISN" => "0047483825",
                "Tempat lahir" => "BATAM",
                "Tgl lahir" => "2006-06-11",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "ISLAM",
                "alamat" => "JL.SIMON TANGKUBOLON HOP.6 NO.35",
                "No. Telp" => "081329953164",
                "kelas" => "",
                "tgl masuk" => "",
            ],
            [
                "NIS" => "20210201405",
                "NAMA" => "MISBACHUL MUNIR AHMAD",
                "NISN" => "0062390941",
                "Tempat lahir" => "BONTANG",
                "Tgl lahir" => "2006-04-22",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "ISLAM",
                "alamat" => "JL. DENPASAR RT.12 KEL.GUNUNG TELIHAN BONTANG BARAT",
                "No. Telp" => "085386778875",
                "kelas" => "",
                "tgl masuk" => "7/5/21",
            ],
            [
                "NIS" => "20210201407",
                "NAMA" => "MUHAMMAD REZA ZULFAHMI",
                "NISN" => "0064212643",
                "Tempat lahir" => "BONTANG",
                "Tgl lahir" => "2006-10-01",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "ISLAM",
                "alamat" => "JL.SLAMET RIYADI RT.41 NO.31 LOKTUAN BONTANG UTARA",
                "No. Telp" => "081347132848",
                "kelas" => "",
                "tgl masuk" => "7/5/21",
            ],
            [
                "NIS" => "20210201408",
                "NAMA" => "MUHAMMAD SUBHAN",
                "NISN" => "0044990879",
                "Tempat lahir" => "BONTANG",
                "Tgl lahir" => "2004-03-06",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "ISLAM",
                "alamat" => "JL. KAPAL FERY RT.08 LOK TUAN BONTANG UTARA",
                "No. Telp" => "081280235773",
                "kelas" => "",
                "tgl masuk" => "7/5/21",
            ],
            [
                "NIS" => "20210201409",
                "NAMA" => "RAHMAT FAREZI",
                "NISN" => "0035110680",
                "Tempat lahir" => "BONTANG",
                "Tgl lahir" => "2003-03-07",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "ISLAM",
                "alamat" => "JL. SUTAN SYARIR RT. 06 KEL. TANJUNG LAUT INDAH KEC. BONTANG SELATAN, BONTANG",
                "No. Telp" => "083152770775",
                "kelas" => "",
                "tgl masuk" => "7/5/21",
            ],
            [
                "NIS" => "20210201410",
                "NAMA" => "RATNA SARI",
                "NISN" => "0067036043",
                "Tempat lahir" => "BONTANG",
                "Tgl lahir" => "2006-04-27",
                "Jenis Kelamin" => "Perempuan",
                "agama" => "ISLAM",
                "alamat" => "JL. POROS BONTANG SAMARINDA KM 5,5 RT.04 KEL.SUKA RAHMAT TELUK PANDAN, KUTA TIMUR",
                "No. Telp" => "085787830658",
                "kelas" => "",
                "tgl masuk" => "7/5/21",
            ],
            [
                "NIS" => "20210201411",
                "NAMA" => "RENO ANDREAS PUTRA",
                "NISN" => "0059040387",
                "Tempat lahir" => "MAMUJU",
                "Tgl lahir" => "2005-01-01",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "ISLAM",
                "alamat" => "JL. WR SUPRATMAN RT. 26 KEL. BEREBAS TENGAH KEC. BONTANG SELATAN, BONTANG",
                "No. Telp" => "082153842850",
                "kelas" => "",
                "tgl masuk" => "7/5/21",
            ],
            [
                "NIS" => "20210201526",
                "NAMA" => "REYVANO PARULIAN",
                "NISN" => "0068125569",
                "Tempat lahir" => "SAMARINDA",
                "Tgl lahir" => "2006-07-09",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "ISLAM",
                "alamat" => "JL.BULU TANGKIS 3 BONTANG UTARA",
                "No. Telp" => "083140170699",
                "kelas" => "",
                "tgl masuk" => "",
            ],
            [
                "NIS" => "20210201421",
                "NAMA" => "ROSSIANO VAN HALLEN",
                "NISN" => "0058142484",
                "Tempat lahir" => "BONTANG",
                "Tgl lahir" => "2005-08-19",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "ISLAM",
                "alamat" => "JL.SIDRAP GUNTUNG",
                "No. Telp" => "085245400227",
                "kelas" => "",
                "tgl masuk" => "7/5/21",
            ],
            [
                "NIS" => "20210201412",
                "NAMA" => "SABILANISA KAMELIANI",
                "NISN" => "0065526699",
                "Tempat lahir" => "BONTANG",
                "Tgl lahir" => "2006-07-22",
                "Jenis Kelamin" => "Perempuan",
                "agama" => "ISLAM",
                "alamat" => "JL.POROS BTG-SMD DESA SUKA RAHMAT RT 14 TELUK PANDAN KUTAI TIMUR",
                "No. Telp" => "081253774920",
                "kelas" => "",
                "tgl masuk" => "7/5/21",
            ],
            [
                "NIS" => "20210201413",
                "NAMA" => "VALENTINO FEBRIANO",
                "NISN" => "0057521289",
                "Tempat lahir" => "SA'DAN PEBULIAN",
                "Tgl lahir" => "2006-02-14",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "KRISTEN",
                "alamat" => "JL.POROS SANGATTA RT.07 KEL.MARTADINATA  TELUK PANDAN KUTAI TIMUR",
                "No. Telp" => "082251992109",
                "kelas" => "",
                "tgl masuk" => "7/5/21",
            ],
            [
                "NIS" => "20210201414",
                "NAMA" => "YOSAFAT JESELIN BORO",
                "NISN" => "0057647612",
                "Tempat lahir" => "BONTANG",
                "Tgl lahir" => "2005-11-19",
                "Jenis Kelamin" => "Laki-laki",
                "agama" => "KRISTEN",
                "alamat" => "JL.SMD BONTANG KM.24 RT.12 SANTAN ULU MARANGKAYU",
                "No. Telp" => "085753553961",
                "kelas" => "",
                "tgl masuk" => "7/5/21",
            ],
        ];

        foreach ($students as $student) {
            Siswa::create([
                "nama" => $student["NAMA"],
                "nis" => $student["NIS"],
                "nisn" => $student["NISN"],
                "tempat_lahir" => $student["Tempat lahir"],
                "tanggal_lahir" => $student["Tgl lahir"],
                "jenis_kelamin" => $student["Jenis Kelamin"],
                "agama" => $student["agama"],
                "alamat" => $student["alamat"],
                "no_telp" => $student["No. Telp"],
            ]);
        }
    }
}
